# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name:"Star Wars"}, { name:"Lord of the Rings"}])
#   Character.create(name:"Luke", movie: movies.first)

puts "Debut"
# Airport.create(code:"BAE", name:"Saint-Pons")
# Airport.create(code:"GAT", name:"Tallard")
# Airport.create(code:"CEQ", name:"Cannes")
# Airport.create(code:"NCE", name:"Nice")
# Airport.create(code:"JLP", name:"Juan-les-Pins")
# Airport.create(code:"JCA", name:"Cannes")
# Airport.create(code:"OBS", name:"Lanas")
# Airport.create(code:"QYR", name:"Barberey-Saint-Sulpice")
# Airport.create(code:"CCF", name:"Carcassonne")
# Airport.create(code:"RDZ", name:"Salles-la-Source")
# Airport.create(code:"QXB", name:"Aix-en-Provence")
# Airport.create(code:"MRS", name:"Marignane")
# Airport.create(code:"QIE", name:"Istres")
# Airport.create(code:"JAH", name:"Aubagne")
# Airport.create(code:"CFR", name:"Carpiquet")
# Airport.create(code:"DOL", name:"Saint-Gatien-des-Bois")
# Airport.create(code:"AUR", name:"Aurillac")
# Airport.create(code:"CNG", name:"Châteaubernard")
# Airport.create(code:"ANG", name:"Champniers")
# Airport.create(code:"RCO", name:"Saint-Agnant")
# Airport.create(code:"LRH", name:"La Rochelle")
# Airport.create(code:"RYN", name:"Médis")
# Airport.create(code:"BOU", name:"Bourges")
# Airport.create(code:"BVE", name:"Brive-la-Gaillarde")
# Airport.create(code:"BVE", name:"Nespouls")
# Airport.create(code:"AJA", name:"Ajaccio")
# Airport.create(code:"FSC", name:"Figari")
# Airport.create(code:"PRP", name:"Propriano")
# Airport.create(code:"SOZ", name:"Ventiseri")
# Airport.create(code:"BIA", name:"Bastia")
# Airport.create(code:"CLY", name:"Calvi")
# Airport.create(code:"DIJ", name:"Longvic")
# Airport.create(code:"LAI", name:"Lannion")
# Airport.create(code:"SBK", name:"Trémuson")
# Airport.create(code:"SBK", name:"Saint-Brieuc")
# Airport.create(code:"MCU", name:"Lépaud")
# Airport.create(code:"EGC", name:"Bergerac")
# Airport.create(code:"PGX", name:"Bassillac")
# Airport.create(code:"QBQ", name:"La Vèze")
# Airport.create(code:"XMF", name:"Courcelles-lès-Montbéliard")
# Airport.create(code:"VAF", name:"Chabeuil")
# Airport.create(code:"EVX", name:"Évreux")
# Airport.create(code:"QTJ", name:"Champhol")
# Airport.create(code:"MXN", name:"Morlaix")
# Airport.create(code:"BES", name:"Guipavas")
# Airport.create(code:"UIP", name:"Pluguffan")
# Airport.create(code:"LDV", name:"Landivisiau")
# Airport.create(code:"FNI", name:"Garons")
# Airport.create(code:"TLS", name:"Blagnac")
# Airport.create(code:"XYT", name:"Toulouse")
# Airport.create(code:"XAC", name:"La Teste-de-Buch")
# Airport.create(code:"BOD", name:"Mérignac")
# Airport.create(code:"MPL", name:"Pérols, Mauguio")
# Airport.create(code:"BZR", name:"Portiragnes, Vias")
# Airport.create(code:"DNR", name:"Pleurtuit")
# Airport.create(code:"RNS", name:"Saint-Jacques-de-la-Lande")
# Airport.create(code:"XSB", name:"Saint-Malo")
# Airport.create(code:"CHR", name:"Déols")
# Airport.create(code:"TUF", name:"Tours")
# Airport.create(code:"GNB", name:"Saint-Étienne-de-Saint-Geoirs")
# Airport.create(code:"AHZ", name:"Huez")
# Airport.create(code:"DLE", name:"Tavaux")
# Airport.create(code:"XDA", name:"Oeyreluy, Seyresse")
# Airport.create(code:"RNE", name:"Saint-Léger-sur-Roanne")
# Airport.create(code:"EBU", name:"Saint-Étienne")
# Airport.create(code:"LPY", name:"Loudes")
# Airport.create(code:"LBY", name:"La Baule-Escoublac")
# Airport.create(code:"NTE", name:"Bouguenais")
# Airport.create(code:"SNR", name:"Montoir-de-Bretagne")
# Airport.create(code:"ORE", name:"Saint-Denis-de-l Hôtel")
# Airport.create(code:"ZAO", name:"Cieurac")
# Airport.create(code:"AGF", name:"Agen")
# Airport.create(code:"MEN", name:"Brenoux")
# Airport.create(code:"ANE", name:"Marcé")
# Airport.create(code:"CET", name:"Cholet")
# Airport.create(code:"CER", name:"Maupertus-sur-Mer, Gonneville")
# Airport.create(code:"GFR", name:"Bréville-sur-Mer")
# Airport.create(code:"XEP", name:"Plivot")
# Airport.create(code:"XCR", name:"Bussy-Lettrée")
# Airport.create(code:"RHE", name:"Reims")
# Airport.create(code:"LVA", name:"Entrammes")
# Airport.create(code:"ENC", name:"Tomblaine, Essey-lès-Nancy")
# Airport.create(code:"XVN", name:"Sommedieue")
# Airport.create(code:"LRT", name:"Plœmeur")
# Airport.create(code:"VNE", name:"Monterblanc")
# Airport.create(code:"MZM", name:"Augny, Marly")
# Airport.create(code:"ETZ", name:"Goin, Pagny-lès-Goin, Vigny, Liéhon et Silly-en-Saulnois")
# Airport.create(code:"NVS", name:"Marzy")
# Airport.create(code:"XDK", name:"Les Moëres")
# Airport.create(code:"LIL", name:"Lesquin")
# Airport.create(code:"HZB", name:"Lestrem, Calonne-sur-la-Lys, Merville")
# Airport.create(code:"XVS", name:"Prouvy, Rouvignies")
# Airport.create(code:"BVA", name:"Tillé")
# Airport.create(code:"CSF", name:"Creil")
# Airport.create(code:"QRV", name:"Roclincourt")
# Airport.create(code:"CQF", name:"Marck")
# Airport.create(code:"LTQ", name:"Le Touquet-Paris-Plage")
# Airport.create(code:"CFE", name:"Aulnat")
# Airport.create(code:"BIQ", name:"Biarritz, Anglet")
# Airport.create(code:"PUF", name:"Uzein")
# Airport.create(code:"LDE", name:"Ossun")
# Airport.create(code:"PGF", name:"Perpignan")
# Airport.create(code:"SXB", name:"Entzheim")
# Airport.create(code:"EAP3", name:"Saint-Louis, Blotzheim")
# Airport.create(code:"CMR", name:"Colmar")
# Airport.create(code:"LYS", name:"Colombier-Saugnieu")
# Airport.create(code:"LYN", name:"Chassieu et Saint-Priest")
# Airport.create(code:"XCD", name:"Champforgeuil")
# Airport.create(code:"SYT", name:"Saint-Yan")
# Airport.create(code:"LME", name:"Arnage")
# Airport.create(code:"CMF", name:"Bourget-du-Lac, La Motte-Servolex, Voglans et Viviers-du-Lac")
# Airport.create(code:"MFX", name:"Les Allues")
# Airport.create(code:"CVF", name:"Saint-Bon-Tarentaise")
# Airport.create(code:"NCY", name:"Meythet")
# Airport.create(code:"QNJ", name:"Annemasse, Ville-La-Grand, Vétraz-Monthoux, Cranves-Sales")
# Airport.create(code:"MVV", name:"Megève")
# Airport.create(code:"JDP", name:"Paris")
# Airport.create(code:"DPE", name:"Saint-Aubin-sur-Scie")
# Airport.create(code:"URO", name:"Boos")
# Airport.create(code:"LEH", name:"Le Havre, Octeville-sur-Mer")
# Airport.create(code:"XLG", name:"Lognes")
# Airport.create(code:"TNF", name:"Toussus-le-Noble")
# Airport.create(code:"NIT", name:"Niort")
# Airport.create(code:"XAB", name:"Abbeville")
# Airport.create(code:"QAM", name:"Amiens")
# Airport.create(code:"LBI", name:"Le Séquestre")
# Airport.create(code:"DCM", name:"Castres")
# Airport.create(code:"CTT", name:"Le Castellet")
# Airport.create(code:"LTT", name:"La Môle")
# Airport.create(code:"TLN", name:"Hyères")
# Airport.create(code:"AVN", name:"Avignon")
# Airport.create(code:"XOG", name:"Orange")
# Airport.create(code:"IDY", name:"L Île-d Yeu")
# Airport.create(code:"EDM", name:"La Roche-sur-Yon")
# Airport.create(code:"LSO", name:"Les Sables-d Olonne")
# Airport.create(code:"PIS", name:"Biard")
# Airport.create(code:"LIG", name:"Limoges")
# Airport.create(code:"EPL", name:"Juvaincourt")
# Airport.create(code:"VTL", name:"Vittel")
# Airport.create(code:"AUF", name:"Branches, Charbuy, Appoigny")
# Airport.create(code:"BOR", name:"Fontaine (Territoire de Belfort)")
# Airport.create(code:"JEV", name:"Évry")
# Airport.create(code:"JPU", name:"Puteaux, Courbevoie")
# Airport.create(code:"LBG", name:"Le Bourget ...")
# Airport.create(code:"ORY", name:"Paray-Vieille-Poste, Orly ...")
# Airport.create(code:"CDG", name:"Roissy, Tremblay, Mitry")
# Airport.create(code:"POX", name:"Cormeilles-en-Vexin")
# Airport.create(code:"AITA", name:"Ville/île desservie")
# Airport.create(code:"BBR", name:"Basse-Terre")
# Airport.create(code:"GBJ", name:"Marie-Galante")
# Airport.create(code:"DSD", name:"Grande Anse - Île de La Désirade")
# Airport.create(code:"LSS", name:"Les Saintes")
# Airport.create(code:"PTP", name:"Pointe-à-Pitre")
# Airport.create(code:"SFC", name:"Saint-François")
# Airport.create(code:"FDF", name:"Fort-de-France - Le Lamentin")
# Airport.create(code:"CAY", name:"Cayenne")
# Airport.create(code:"GSI", name:"Grand-Santi")
# Airport.create(code:"MPY", name:"Maripasoula")
# Airport.create(code:"OXP", name:"Saint-Georges-de-l Oyapock")
# Airport.create(code:"LDX", name:"Saint-Laurent-du-Maroni")
# Airport.create(code:"REI", name:"Régina")
# Airport.create(code:"XAU", name:"Saül")
# Airport.create(code:"RUN", name:"Saint-Denis")
# Airport.create(code:"ZSE", name:"Saint-Pierre")
# Airport.create(code:"FSP", name:"Saint-Pierre")
# Airport.create(code:"MQC", name:"Miquelon")
# Airport.create(code:"DZA", name:"Dzaoudzi")
# Airport.create(code:"SBH", name:"Saint-Barthélemy")
# Airport.create(code:"SFG", name:"Saint-Martin")
# Airport.create(code:"FUT", name:"Leava - Futuna (île)")
# Airport.create(code:"WLS", name:"Mata-Utu - Wallis (île)")
# Airport.create(code:"AHE", name:"Ahe")
# Airport.create(code:"AAA", name:"Anaa")
# Airport.create(code:"APK", name:"Apataki")
# Airport.create(code:"RKA", name:"Aratika")
# Airport.create(code:"AGR", name:"Arutua")
# Airport.create(code:"BOB", name:"Bora Bora")
# Airport.create(code:"FAC", name:"Faaite")
# Airport.create(code:"FHZ", name:"Fakahina")
# Airport.create(code:"FAV", name:"Fakarava")
# Airport.create(code:"FGU", name:"Fangatau")
# Airport.create(code:"HOI", name:"Hao")
# Airport.create(code:"HHZ", name:"Hikueru")
# Airport.create(code:"AUQ", name:"Hiva Oa")
# Airport.create(code:"HUH", name:"Huahine")
# Airport.create(code:"KXU", name:"Katiu")
# Airport.create(code:"KHZ", name:"Kauehi")
# Airport.create(code:"KKR", name:"Kaukura")
# Airport.create(code:"MKP", name:"Makemo")
# Airport.create(code:"XMH", name:"Manihi")
# Airport.create(code:"MVT", name:"Mataiva")
# Airport.create(code:"MAU", name:"Maupiti")
# Airport.create(code:"MOZ", name:"Moorea")
# Airport.create(code:"NAU", name:"Napuka")
# Airport.create(code:"NHV", name:"Nuku Hiva")
# Airport.create(code:"NUK", name:"Nukutavake")
# Airport.create(code:"PPT", name:"Papeete")
# Airport.create(code:"PKP", name:"Puka Puka")
# Airport.create(code:"PUK", name:"Pukarua")
# Airport.create(code:"RFP", name:"Raiatea")
# Airport.create(code:"RVV", name:"Raivavae")
# Airport.create(code:"RGI", name:"Rangiroa")
# Airport.create(code:"REA", name:"Reao")
# Airport.create(code:"RUR", name:"Rurutu")
# Airport.create(code:"TKP", name:"Takapoto")
# Airport.create(code:"TKX", name:"Takaroa")
# Airport.create(code:"TJN", name:"Takume")
# Airport.create(code:"TKV", name:"Tatakoto")
# Airport.create(code:"TTI", name:"Tetiaroa")
# Airport.create(code:"TIH", name:"Tikehau")
# Airport.create(code:"TUB", name:"Tubuai")
# Airport.create(code:"ZTA", name:"Tureia")
# Airport.create(code:"UAH", name:"Ua Huka")
# Airport.create(code:"UAP", name:"Ua Pou")
# Airport.create(code:"VHZ", name:"Vahitahi")
# Airport.create(code:"GMR", name:"Totegegie")
# Airport.create(code:"TGJ", name:"Tiga")
# Airport.create(code:"BMY", name:"Île Art")
# Airport.create(code:"KNQ", name:"Koné")
# Airport.create(code:"ILP", name:"Île des Pins")
# Airport.create(code:"KOC", name:"Koumac")
# Airport.create(code:"LIF", name:"Lifou")
# Airport.create(code:"GEA", name:"Nouméa")
# Airport.create(code:"PUV", name:"Poum")
# Airport.create(code:"MEE", name:"Maré")
# Airport.create(code:"TOU", name:"Touho")
# Airport.create(code:"UVE", name:"Ouvéa")
# Airport.create(code:"NOU", name:"Nouméa")


# for i in 1..1

#   f = Flight.new
#   departure = Airport.find(rand(1..Airport.count))
#   arrival = Airport.find(rand(1..Airport.count))
#   while (arrival == departure)
#     arrival = Airport.find(rand(1..Airport.count))
#   end
#   departure_date = Time.now + rand(30)*60*60*24 + rand(24)*60*60
#   duration = rand(30..100)

#   f.departure_airport = departure
#   f.arrival_airport = arrival
#   f.departure_date = departure_date
#   f.duration = duration
#   f.save

# end

Airport.create(code:"XBK", name:"Jasseron")
Airport.create(code:"GVA", name:"Grand-Saconnex et Meyrin en Suisse")
Airport.create(code:"XCY", name:"Château-Thierry")
Airport.create(code:"XMU", name:"Toulon-sur-Allier")
Airport.create(code:"VHY", name:"Charmeil, Saint-Rémy-en-Rollat")

f12 = Flight.create(departure_airport: Airport.first, arrival_airport: Airport.second)
f13 = Flight.create(departure_airport: Airport.first, arrival_airport: Airport.third)
f14 = Flight.create(departure_airport: Airport.first, arrival_airport: Airport.fourth)
f15a = Flight.create(departure_airport: Airport.first, arrival_airport: Airport.fifth)
f15b = Flight.create(departure_airport: Airport.first, arrival_airport: Airport.fifth)
f15c = Flight.create(departure_airport: Airport.first, arrival_airport: Airport.fifth)

f21 = Flight.create(departure_airport: Airport.second, arrival_airport: Airport.first)
f31 = Flight.create(departure_airport: Airport.third, arrival_airport: Airport.first)
f41 = Flight.create(departure_airport: Airport.fourth, arrival_airport: Airport.first)
f51 = Flight.create(departure_airport: Airport.fifth, arrival_airport: Airport.first)

a1 = Airport.first
a2 = Airport.second
a3 = Airport.third
a4 = Airport.fourth
a5 = Airport.fifth

fs = Flight.where(departure_airport: a1,arrival_airport: a2 )

puts "Fin"
