# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47e9152f135017e752b2d3b6b3303925d2028764caedbaee257479a19909b4ecb9798dc096e75aaa0ceb2ff22f99aabade44ee35da71e413e8f7f6a1b2927f8a

test:
  secret_key_base: cf3d0d6845e2749e2ec49dab3b9f33b2473a3719a8d0f4f9633f4943a44db9738ac7a391091cd72f63c48faf9ede79d264bd874d134bc88cd1e2a9c2b587d58f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
