# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5aa52359f01bfdd8c29e8427fb3d909d02c414e62fb7a76992ed55919721fe293b78f5267290f34ea1b409cca867a13ee9ec207c51086b59d777a69b7c16c6f1

test:
  secret_key_base: 9ad5b79037b27c77143c7fe9b9695b764ebff62a2fdb76ad37335b74b47bf079f67f205e75b61bf1743bd002e7cab764d44781c68e036e955ce7237987ba30bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
